Added a "S" to the pypi URL to prevent 403
Pypi disabled http api access so the url needs to be https to be successful;

[before change]

$ raxmon-version-check
Traceback (most recent call last):
  File "/Users/darren.carpenter/raxmon/lib/python2.7/site-packages/raxmon_cli/common.py", line 130, in run_action
    callback(instance, options, args, done)
  File "/Users/darren.carpenter/raxmon/bin/raxmon-version-check", line 35, in callback
    f = urllib2.urlopen(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: SSL is required

[after change]

$ raxmon-version-check
Current version: 0.7.3
Latest version: 0.7.3